[package]
name = "executor"
version = "0.1.0"
authors = ["Max Meldrum <mmeldrum@kth.se>"]

[dependencies]
kompact = {git = "https://github.com/kompics/kompact", branch = "master", features = ["protobuf"]}
protobuf = "2.0"
bytes = "0.4"

[build-dependencies]
protoc-rust = "2.0"
